"""add context fields to chat_sessions

Revision ID: 46f9a3f47a02
Revises: ccda85145b1d
Create Date: 2026-04-05 20:42:19.286447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f9a3f47a02'
down_revision = 'ccda85145b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_ds_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('selected_doc_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('selected_doc_ids')
        batch_op.drop_column('selected_ds_id')

    # ### end Alembic commands ###
