"""add source to design_system_assets

Revision ID: 5bdbfb24c2d8
Revises: b5960146a61c
Create Date: 2026-04-07 13:14:59.320616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdbfb24c2d8'
down_revision = 'b5960146a61c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('design_system_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))

    op.execute("UPDATE design_system_assets SET source = 'raster' WHERE source IS NULL")

    with op.batch_alter_table('design_system_assets', schema=None) as batch_op:
        batch_op.alter_column('source', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_system_assets', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
