"""add is_default to design_systems

Revision ID: 7ff4f43377a2
Revises: 7b78eef4e1fd
Create Date: 2026-04-05 16:14:23.964553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff4f43377a2'
down_revision = '7b78eef4e1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_systems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_systems', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
