"""add brand_guidelines and slide_templates to design_systems

Revision ID: b5960146a61c
Revises: d0d2da590f52
Create Date: 2026-04-05 23:13:44.562204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5960146a61c'
down_revision = 'd0d2da590f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_systems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_guidelines', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('slide_templates', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_systems', schema=None) as batch_op:
        batch_op.drop_column('slide_templates')
        batch_op.drop_column('brand_guidelines')

    # ### end Alembic commands ###
