"""add review_report to messages

Revision ID: d0d2da590f52
Revises: 46f9a3f47a02
Create Date: 2026-04-05 21:25:08.800242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d2da590f52'
down_revision = '46f9a3f47a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_report', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('review_report')

    # ### end Alembic commands ###
